arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-localization-file-bn: app_localizations_bn.dart
output-localization-file-en: app_localizations_en.dart

output-dir: lib/l10n